server.port=8081
spring.application.name=auth-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Keep the DB bypass for now
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration